### ISSUE TITLE
Add Missing files

### ISSUE THREAD

**Issue by kpatel427** [marislab/pptx-pdx-fusion-analysis#2]
Hi Komal, 

Can you please add the following missing files in your repo?
1.	PPTC_Fusion_Human-MC_v2.txt (driver_fusions.R)
2.	ALL_cytogenetics_translocations_CM_v2.txt (driver_fusions.R)
3.	genes.tsv (driver_fusions.R)
4.	Cosmic_gene_census.csv (summary.R)
5.	kinases.txt (summary.R)
6.	TRANSFAC_TF.txt (summary.R)

Thanks so much!

Best,
Khushbu

**Comment by komalsrathi** [comment]
Sure - I will add them on figshare
